name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp pyinstaller
    
    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --console --name "YouTube_Downloader" youtube_downloader.py
    
    - name: Build with PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --console --name "YouTube_Downloader" youtube_downloader.py
    
    - name: Build with PyInstaller (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --console --name "YouTube_Downloader" youtube_downloader.py
    
    - name: Upload Windows Executable
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: YouTube_Downloader-Windows
        path: dist/YouTube_Downloader.exe
    
    - name: Upload macOS Executable
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: YouTube_Downloader-macOS
        path: dist/YouTube_Downloader
    
    - name: Upload Linux Executable
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: YouTube_Downloader-Linux
        path: dist/YouTube_Downloader
